import { cn } from "@/lib/utils";

/** Rótulos pt-PT de todos os estados reais da API (secção 7 da especificação). */
const LABELS: Record<string, string> = {
  Draft: "Rascunho",
  Planned: "Planeado",
  Requested: "Pedido",
  Scheduled: "Agendado",
  Created: "Criada",
  Submitted: "Submetido",
  Started: "Iniciada",
  UnderReview: "Em análise",
  UnderAnalysis: "Em análise",
  UnderTechnicalReview: "Em análise técnica",
  UnderValidation: "Em validação",
  UnderInvestigation: "Em investigação",
  DocumentValidation: "Validação documental",
  Validating: "Em validação",
  TechnicalValidation: "Validação técnica",
  LegalValidation: "Validação jurídica",
  DecisionPending: "Decisão pendente",
  PendingPayment: "Pendente de pagamento",
  Pending: "Pendente",
  Calculated: "Calculado",
  Measured: "Medida",
  Liquidated: "Liquidado",
  PartiallyPaid: "Parcialmente pago",
  PartiallyUsed: "Parcialmente consumida",
  PartiallyDispatched: "Parcialmente despachado",
  Approved: "Aprovado",
  Validated: "Validado",
  Authorized: "Autorizado",
  Issued: "Emitido",
  Available: "Disponível",
  AllocatedToLot: "Alocada a lote",
  Active: "Activo",
  InProgress: "Em curso",
  InTransit: "Em trânsito",
  Open: "Aberto",
  Registered: "Registada",
  InLot: "Em lote",
  Paid: "Pago",
  Stored: "Armazenada",
  Dispatched: "Despachado",
  Completed: "Concluído",
  Closed: "Fechado",
  Consumed: "Consumida",
  Exported: "Exportada",
  Fined: "Multado",
  Appealed: "Em recurso",
  Suspended: "Suspenso",
  Rejected: "Rejeitado",
  Expired: "Expirado",
  Cancelled: "Cancelado",
  Refunded: "Reembolsado",
  Inactive: "Inactivo",
  // Árvores (TreeStatus)
  Inventoried: "Inventariada",
  AuthorizedForExploitation: "Autorizada para exploração",
  Harvested: "Abatida",
  // Stock em entreposto (WarehouseStockStatus)
  Reserved: "Reservado",
  Blocked: "Bloqueado",
  // Sobreposição de Área (mock — Registo de Área)
  Conforme: "Conforme",
  ConformeComReserva: "Conforme com reserva",
  NaoConforme: "Não conforme",
  // Instrumentos técnicos da Concessão (mock)
  Missing: "Em falta",
  // Licenciamento standalone (mock)
  PrecheckVerification: "Em verificação de pré-condições",
};

/** Tons por estado — verde/sucesso, amarelo/em curso, azul/informativo, vermelho/bloqueado, cinza/neutro. */
const TONES: Record<string, string> = {
  Draft: "bg-muted text-muted-foreground",
  Planned: "bg-muted text-muted-foreground",
  Created: "bg-muted text-muted-foreground",
  Requested: "bg-info/15 text-info",
  Scheduled: "bg-info/15 text-info",
  Submitted: "bg-info/15 text-info",
  Started: "bg-info/15 text-info",
  Pending: "bg-info/15 text-info",
  Calculated: "bg-info/15 text-info",
  Measured: "bg-info/15 text-info",
  Open: "bg-info/15 text-info",
  Registered: "bg-info/15 text-info",
  InLot: "bg-info/15 text-info",
  AllocatedToLot: "bg-info/15 text-info",
  Dispatched: "bg-info/15 text-info",
  UnderReview: "bg-warning/20 text-warning-foreground",
  UnderAnalysis: "bg-warning/20 text-warning-foreground",
  UnderTechnicalReview: "bg-warning/20 text-warning-foreground",
  UnderValidation: "bg-warning/20 text-warning-foreground",
  UnderInvestigation: "bg-warning/20 text-warning-foreground",
  DocumentValidation: "bg-warning/20 text-warning-foreground",
  Validating: "bg-warning/20 text-warning-foreground",
  TechnicalValidation: "bg-warning/20 text-warning-foreground",
  LegalValidation: "bg-warning/20 text-warning-foreground",
  DecisionPending: "bg-warning/20 text-warning-foreground",
  PendingPayment: "bg-warning/20 text-warning-foreground",
  Liquidated: "bg-warning/20 text-warning-foreground",
  PartiallyPaid: "bg-warning/20 text-warning-foreground",
  PartiallyUsed: "bg-warning/20 text-warning-foreground",
  PartiallyDispatched: "bg-warning/20 text-warning-foreground",
  InProgress: "bg-warning/20 text-warning-foreground",
  InTransit: "bg-warning/20 text-warning-foreground",
  Appealed: "bg-warning/20 text-warning-foreground",
  Approved: "bg-success/15 text-success",
  Validated: "bg-success/15 text-success",
  Authorized: "bg-success/15 text-success",
  Issued: "bg-success/15 text-success",
  Available: "bg-success/15 text-success",
  Paid: "bg-success/15 text-success",
  Stored: "bg-success/15 text-success",
  Active: "bg-primary text-primary-foreground",
  Completed: "bg-primary text-primary-foreground",
  Closed: "bg-primary text-primary-foreground",
  Exported: "bg-primary text-primary-foreground",
  Suspended: "bg-destructive/15 text-destructive",
  Rejected: "bg-destructive/15 text-destructive",
  Fined: "bg-destructive/15 text-destructive",
  Expired: "bg-foreground/70 text-background",
  Consumed: "bg-foreground/70 text-background",
  Cancelled: "bg-foreground/70 text-background",
  Refunded: "bg-muted text-muted-foreground",
  Inactive: "bg-muted text-muted-foreground",
  // Árvores (TreeStatus)
  Inventoried: "bg-muted text-muted-foreground",
  AuthorizedForExploitation: "bg-warning/20 text-warning-foreground",
  Harvested: "bg-primary text-primary-foreground",
  // Stock em entreposto (WarehouseStockStatus)
  Reserved: "bg-warning/20 text-warning-foreground",
  Blocked: "bg-destructive/15 text-destructive",
  // Sobreposição de Área (mock — Registo de Área)
  Conforme: "bg-success/15 text-success",
  ConformeComReserva: "bg-warning/20 text-warning-foreground",
  NaoConforme: "bg-destructive/15 text-destructive",
  // Instrumentos técnicos da Concessão (mock)
  Missing: "bg-muted text-muted-foreground",
  // Licenciamento standalone (mock)
  PrecheckVerification: "bg-warning/20 text-warning-foreground",
};

export const StatusBadge = ({ status, className }: { status: string; className?: string }) => (
  <span
    className={cn(
      "inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold",
      TONES[status] ?? "bg-muted text-muted-foreground",
      className,
    )}
  >
    {LABELS[status] ?? status}
  </span>
);

export default StatusBadge;
